### ISSUE TITLE
think u meant to install standard and not standardjs

### ISSUE THREAD

**Issue by jimmywarting** [nthomas20/redis-graph-light#5]
https://github.com/nthomas20/redis-graph-light/blob/6c2ddae1a7940f1306c7372603fc65b8f1aac692/package.json#L17

**Comment by nthomas20** [comment]
Yep, I definitely should update this -- this was something like 3 years ago, I think -- haven't used this in a while, it seems! Thanks for the alert!

**Comment by jimmywarting** [comment]
Did the same thing, better watch out for bad similar names that might do harm, you decided to warn some ppl on github

**Comment by nthomas20** [comment]
Corrected and republished! Thx again
